;subrutina de BIN A BCD

cblock				;en la subrutina no se debe fijar la direccion
	BCD_CENTENAS	;de la ram. se toma a continuacion de la ultima asignada
	BCD_DECENAS
	BCD_UNIDADES
endc

BIN_A_BCD
	CLRF	BCD_CENTENAS
	CLRF	BCD_DECENAS
	MOVWF	BCD_UNIDADES
	
BCD_RESTA10
	MOVLW	.10
	SUBWF	BCD_UNIDADES,W
	BTFSS	STATUS,C
	GOTO	BIN_BCD_FIN
	
BCD_INCREMENTA_DECENAS
	MOVWF	BCD_UNIDADES
	INCF	BCF_DECENAS,F
	MOVLW	.10
	SUBWF	BCD_DECENAS,W
	BTFSS	STATUS,C
	GOTO	BCD_RESTA10
	
BIN_BCD_FIN
	SWAPF	BCD_DECENAS,W
	ADDWF	BCD_UNIDADES,W
	RETURN
