#include "p18f4550.inc"
#include "config.inc"
#define	S_PIR	PORTA,0

cblock 0x10
	PIR
	CONTADOR_UNI
	CONTADOR_DECI
endc

	org		0x0000
	goto	SETUP
	org 	0x0020
	
SETUP:
	movlw	0x62
	movwf	OSCCON
	MOVLW	0X0F
	MOVWF	ADCON1
	CLRF	TRISD				;PARA EL LCD
	CLRF	LATD
	BSF		TRISA,1				;SENSOR PIR
	MOVLW	.0
	CALL	lcd_fila0			;MENSAJE EN LA LINEA 0
	MOVLW	.0
	CALL	lcd_print
	MOVLW	.0
	CALL	lcd_fila1			;CONTADOR EN LA LINEA 1
	CLRF	CONTADOR_UNI
	MOVLW	.30
	ADDWF	CONTADOR_UNI
	CALL	lcd_char	
	CLRF	CONTADOR_DECI
	MOVLW	.30
	ADDWF	CONTADOR_DECI
	CALL	lcd_char

LOOP:
UNIDADES:
	BTFSS	PORTA,1
	GOTO	LOOP
	INCF	CONTADOR_UNI
	MOVLW	.30
	ADDWF	CONTADOR_UNI
	CALL	lcd_char
	MOVLW	.9
	CPFSEQ	CONTADOR_UNI,W
	GOTO	LOPP		;FALSO
	CALL	DECIMALES;VERDADERO
	GOTO	LOOP
	
DECIMALES:
	CLRF	CONTADOR_UNI
	MOVLW	.30
	ADDWF	CONTADOR_UNI
	CALL	lcd_char
	INCF	CONTADOR_DECI
	MOVLW	.30
	ADDWF	CONTADOR_DECI
	CALL	lcd_char
	return
	
mensajes:
	data "contador PIR " 			;0 al 13
	DB	CONTADOR_UNI,CONTADOR_DECI	;14 y 15
	
	
#include "retardos.inc"
#include "pantallaLCD.inc"

	END
